Source/buildimplementationpascal.go
Type for local variable was not correct for
pascal implementation functions with struct
return type. This fixes issue #4
=> Fix issue in pascal implementation generation

Source/buildbindingpascal.go, Source/languagepascal.go
This fixes Issue #9 
Struct results should be assigned directly to the result (@Result)
Since structs are passed by pointers, there is no need for the 'out' keyword
=> Fix pascal impl&binding with struct returns

Source/buildbindingpython.go
Change python binder struct-in parameter to call-by-reference.
This fixes Issue #16
=> Fis issue in python binder for struct-in parameter

Documentation/IDL.md, Source/componentdefinition.go
Fixes https://github.com/Autodesk/AutomaticComponentToolkit/issues/26 :
A parent-class MUST be defined before being used in the XML.
=> Ensure ordering of classes

Source/buildimplementationpascal.go
libsupport_exception.pas and libsupport_interfaces.pas had dependencies to each other.
The interface-block of both of the unis don't need the other one. Therefore putting the 'uses' into the implementation-block fixes the issue #29
=> Fix circular dependency in pascal implmenetation

Source/buildimplementationcpp.go
This affects the c++ implementation generation.
Add a second exception constructor that takes as second parameter a custom exception message.
This allows the user to throw exceptions that contains additional information as text. 
The custom message is already implemented for pascal.
=> Allow custom error messages for c++ impl

Source/buildimplementationcpp.go
It now generates a default implementation that propagates the last error string correctly.
=> Fix for #85: Improved default error handling in C++ Stub

Source/buildimplementationcpp.go, Source/languagec.go
A new inline function in the types header can translate an error code into a user readable string.
=> Added Language String support for C++ implementation (Issue #83)

.gitignore, Source/buildbindingccpp.go
When compiling the c++ act bindings for a cross component interface project the visual studio compiler outputs warningsof the form:
```
typedef struct {
PAbstractCAMBase_GetLastErrorPtr m_Base_GetLastError;
PAbstractCAMBase_ReleaseInstancePtr m_Base_ReleaseInstance;
PAbstractCAMBase_AcquireInstancePtr m_Base_AcquireInstance;
PAbstractCAMBase_GetVersionPtr m_Base_GetVersion;
PAbstractCAMBase_GetSymbolLookupMethodPtr m_Base_GetSymbolLookupMethod;
} sAbstractCAMFunctionTableBase;
typedef struct : sAbstractCAMFunctionTableBase {
PAbstractCAMLinking_CreateLinkerPtr m_Linking_CreateLinker;
PAbstractCAMLinking_QueryStrategyPtr m_Linking_QueryStrategy;
} sAbstractCAMFunctionTableLinking;
```
This appars to be the issue in https://developercommunity.visualstudio.com/content/problem/1034754/warning- …
=> Fix visual studio 16.6 warning in the cpp bindings

Source/buildimplementationcpp.go
If there is an out optionalclass value, the code generator creates a base result variable:
IBase * pBaseHandlerInstance(nullptr);
This leads to a compile error of the implementation. The class should be the correct output class, like
ISignalHandler * pBaseHandlerInstance(nullptr);
=>  Out optionalclass is not generating valid code in C++ implementation. #101 

Source/buildimplementationcpp.go
Co-authored-by: Alexander Oster <Alexander.Oster@autodesk.com>
=> Fixed issue101 (#111)

Source/buildbindinggo.go
This PR prepares the go bindings for future additions by consolidating the code format.
Changes in this PR:
- Run `go fmt Source/buildbindinggo.go`
- Make all `Wrapper` methods receiver be passed by value as there is no need to use a pointer.
=> Format go bindings code

Source/buildbindingccpp.go
ACT-generated bindings don't contain a mapping between error codes and human-readable names and descriptions. If exception text gets printed this can result in very unfriendly error messages for developers and (if a crash escapes into the wild) users.
This PR adds methods to the binding exception class to get the more human-friendly error name and description specified in the IDL file. The `what()` method is reworked to give a default error text with the error name and description, not the number code.
=> Better error messages (CrossComponentInheritance)

Source/buildbindingccpp.go
ACT-generated bindings don't contain a mapping between error codes and human-readable names and descriptions. If exception text gets printed this can result in very unfriendly error messages for developers and (if a crash escapes into the wild) users.
This PR adds methods to the binding exception class to get the more human-friendly error name and description specified in the IDL file. The `what()` method is reworked to give a default error text with the error name and description, not the number code.
=> Better error messages (develop)

Source/buildbindingcsharp.go
The callback instead of a constant value should be used.
=> Fix csharp callback issue.

Source/buildbindingccpp.go
Codacy reports failures for these code
=> Fix codacy issue in cpp binding.

Source/buildbindingcsharp.go
Changed default access specifier for class in C# bindings
=> Make C# class public

Source/buildbindingccpp.go
My recent change to improve error messages introduced a warning into the generated binding because the initialiser list for the exception constructor is not in the order in which members are declared. This PR should fix it.
=> Fix initialisation order warning

Build/build.sh
Make GOARCH, GOOS and GOARM environment visible to `go` compiler
=> Fix MacOS build script

Source/buildbindingcsharp.go
@martinweismann PTAL.
Example for the generated binding code.
=> Do null check for C# pointer to avoid crash.

Source/languagec.go
Structs were declared like so
```C++
typedef struct {
} sFoo;
```
which made it impossible to predeclare them.
Do it like so
```C++
typedef struct sFoo {
} sFoo;
```
=> Allow struct predeclaration (CrossComponentInheritance)

Source/languagec.go
Structs were declared like so
```C++
typedef struct {
} sFoo;
```
which made it impossible to predeclare them.
Do it like so
```C++
typedef struct sFoo {
} sFoo;
```
=> Allow struct predeclaration (develop)

Build/build.sh, Source/buildimplementationcpp.go, Source/buildimplementationjs.go, Source/componentdefinition.go
Remove the need for manual editing of files generated for both Mac and Windows so that my Windows project compiles.
Perhaps controversially, I added `nameIsValidEnumOptionIdentifier` to allow ACT to accept enum identifiers which begin with a lowercase letter.  I also allowed descriptions to be proceeded by a space.  We'll want to revert these things in the medium term and fix in the xml generation code instead.
=> Mac port for windows only functionality

Build/build.sh, Source/buildimplementationcpp.go, Source/buildimplementationjs.go, Source/componentdefinition.go
Return out aguments from javascript methods as an array.
For example, where x and y are out arguments.
`const [x, y] = obj.method(z); `
=> Fix 'out' arguments for javascript bindings
